# Book settings
title: Python Notes for Linguistics
author: Alvin Chen
logo: ./images/ntnu03.png
copyright: "2020 Alvin Chen"
latex:
  latex_documents:
    targetname: book.tex
parse:
  myst_extended_syntax: true
html:
    home_page_in_navbar: false
    extra_navbar: |
        <div style="text-align:left">
            <a href="https://alvinchen.myftp.org/" target='_blank'>Alvin Chen's Homepage</a>
        </div>
execute:
  execute_notebooks: auto
  exclude_patterns:
    - 'nlp/seq-to-seq.ipynb'
    - 'nlp/text-gen-lstm-v2.ipynb'
    - 'nlp/transfer-learning-sent-encoding.ipynb'
    - 'nlp/hyperparameter-tuning.ipynb'
    - 'nlp/sentiment-analysis-marc.ipynb'
    - 'nlp/sentiment-analysis-svm-hyperparameter-marc.ipynb'
    - 'nlp/sentiment-analysis-using-bert-chinese.ipynb'
    - 'nlp/sentiment-analysis-using-bert.ipynb'
    - 'nlp/transfer-learning-sent-encoding-chinese.ipynb'
    - 'nlp/ktrain-tutorial-explaining-predictions.ipynb'
sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
repository:
  url                       : https://github.com/alvinntnu/python-notes
  branch                    : master
launch_buttons:
  colab_url: "https://colab.research.google.com"

    