# Book settings
title: Python Notes for Linguistics
author: Alvin Chen
logo: ntnu03.png
copyright: "2020 Alvin Chen"
latex:
  latex_documents:
    targetname: book.tex
parse:
  myst_extended_syntax: true
html:
    extra_navbar: |
        <div style="text-align:left">
            <a href="https://alvinchen.myftp.org/" target='_blank'>Alvin Chen's Homepage</a>
        </div>
execute:
  exclude_patterns:
    - 'seq-to-seq.ipynb'
    - 'text-gen-lstm-v2.ipynb'
    - 'transfer-learning-sent-encoding.ipynb'
    - 'hyperparameter-tuning.ipynb'
sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
    